### ISSUE TITLE
Recm:Add required pkgs in requirements.txt ; Tks

### ISSUE THREAD

**Issue by zygmcc** [JinghuiZhou/awesome_face_antispoofing#10]
requirements.txt now blank，wish add pkgs with versions ， Tks a lot

**Comment by JinghuiZhou** [comment]
OK，I will update it later.  thx ！

**Comment by zygmcc** [comment]
pip install https://download.pytorch.org/whl/cu80/torch-1.0.0-cp35-cp35m-win_amd64.whl
pip install torchvision
pip install opencv-python
pip install torchnet 
pip install tqdm
pip install torchsummary
pip install matplotlib
pip install fire
conda install scikit-learn
