### ISSUE TITLE
you know what I mean...

### ISSUE THREAD

**Issue by zygmcc** [JinghuiZhou/awesome_face_antispoofing#11]
![image](https://user-images.githubusercontent.com/20073054/50571572-f544a080-0de8-11e9-8338-e80f3b685dd9.png)

**Comment by zygmcc** [comment]
problem is about face_alignment itself... Seems dectect wrong

**Comment by JinghuiZhou** [comment]
I will visualize all detected faces to check it， thx！

**Comment by JinghuiZhou** [comment]
I have fixed the bug of choice wrong face in multiple detected faces with standard of coordinates. But some error faces exist because of landmark detection errors.  You can check readme. Thx

**Comment by JinghuiZhou** [comment]
https://github.com/JinghuiZhou/awesome_face_antispoofing/blob/master/data/showcropface_train.jpg The cropped training faces are shown here. I use standard of landmarks to select expected faces. But the situation you described still happens. Do you have any suggestion?
