### ISSUE TITLE
Need inference.py

### ISSUE THREAD

**Issue by XinyuDu** [JinghuiZhou/awesome_face_antispoofing#13]
I noticed that you have uploaded some pretrained models. Is there any inference script for test these models?  thx.

**Comment by JinghuiZhou** [comment]
I will update an inference script later，THX！

**Comment by JinghuiZhou** [comment]
I have updata an inference script. And you can check the usage in readme. Meanwhile, there are some errors in my uploaded checkpoints. I will load right checkpoints later. THX
