### ISSUE TITLE
Need some sample data also.

### ISSUE THREAD

**Issue by 74981** [JinghuiZhou/awesome_face_antispoofing#2]
Please me how to train.

 python3 main.py train
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from data import myData
ModuleNotFoundError: No module named 'data'

**Comment by JinghuiZhou** [comment]
I will update myData soon. Thanks.

**Comment by 74981** [comment]
Thanks. I am setting up project. Will require help. is there something without cuda lib? which you can provide me so that i could test face snoofing ? Please help if you can provide.

thanks in adcance.
