### ISSUE TITLE
Missing "from data import myData" 

### ISSUE THREAD

**Issue by 74981** [JinghuiZhou/awesome_face_antispoofing#3]
i am not able to identify data. please help. Need your help here.

**Comment by JinghuiZhou** [comment]
I will update myData soon. Thanks.

**Comment by JinghuiZhou** [comment]
I have updated data.

**Comment by 74981** [comment]
Thanks. I am setting up project. Will require help. is there something without cuda lib? which you can provide me so that i could test face snoofing ? Please help if you can provide.

thanks in adcance.
