### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by 74981** [JinghuiZhou/awesome_face_antispoofing#4]
Can you please let me know what path or value i need to put here-

   env = model # visdom 环境
   train_root = '' # 训练集存放路径
   val_root = '' # 验证集存放路径
   test_root = 'data/AgriculturalDisease_testA/' # 测试集存放路径

some sample required please.

**Comment by JinghuiZhou** [comment]
Hello, I will modify my code.  this roots are removed.

**Comment by 74981** [comment]
Ok Please update me once done. Thanks for prompt reply.
