### ISSUE TITLE
I am new need help.

### ISSUE THREAD

**Issue by 74981** [JinghuiZhou/awesome_face_antispoofing#5]
myData, test= False
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    fire.Fire()
  File "/anaconda3/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/anaconda3/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/anaconda3/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 100, in train
    data_source='none')
  File "/Users/b0074981/Desktop/facelivenesspython/2/data/require_dataset.py", line 39, in __init__
    fopen = open(filedir,'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/cv/zjh/aich/dataset/raw/client_train_raw.txt'

Please help

**Comment by 74981** [comment]
in case you have any issues for upload then please send me those sample data or complete sample project with some data at niranjan.bhupendra@gmail.com

help really appreciated.

Thanks in advance.

**Comment by JinghuiZhou** [comment]
I will upload data and corresponding landmark file on GOOGLE DRIVE. And I will update REAME.md with this file.

**Comment by 74981** [comment]
Ok Thanks really appriciatated. Let me know once google drive link updated.

**Comment by JinghuiZhou** [comment]
I have updated google drive and written it in README

**Comment by 74981** [comment]
Ok i downloaded drive file but while unzipping it its always giving FlowNet2_checkpoint.pth.tar.cpgz

Please guide me.

**Comment by JinghuiZhou** [comment]
I find that I give a wrong url in README. And I have changed it.

**Comment by 74981** [comment]
Also from where these files will get reference as its not available?

 train_filelists=[
    ['/home/cv/zjh/aich/dataset/raw/ClientRaw','/home/cv/zjh/aich/dataset/raw/client_train_raw.txt',ATTACK],
    ['/home/cv/zjh/aich/dataset/raw/ImposterRaw','/home/cv/zjh/aich/dataset/raw/imposter_train_raw.txt',GENUINE]
    ]
   test_filelists=[
    ['/home/cv/zjh/aich/dataset/raw/ClientRaw','/home/cv/zjh/aich/dataset/raw/client_test_raw.txt',ATTACK],
    ['/home/cv/zjh/aich/dataset/raw/ImposterRaw','/home/cv/zjh/aich/dataset/raw/imposter_test_raw.txt',GENUINE]
    ]

**Comment by 74981** [comment]
Ok let me download. Thanks

**Comment by JinghuiZhou** [comment]
unzip raw, it contains filelists.

**Comment by 74981** [comment]
Ok I am trying. Will ping you for any help required.

Thank you very much.
