### ISSUE TITLE
Do you have the trained model. It is  so slow to train this model in my computer. 

### ISSUE THREAD

**Issue by yiqigo0215** [JinghuiZhou/awesome_face_antispoofing#7]

**Comment by yiqigo0215** [comment]
Do you have the trained model. It is  so slow to train this model in my computer.

**Comment by JinghuiZhou** [comment]
OK， I will upload trained model lalter. Thx

**Comment by JinghuiZhou** [comment]
Done. You can check it in readme.

**Comment by PooriaKhani** [comment]
> Done. You can check it in readme.

I can not find the trained model

**Comment by theVmagnificient** [comment]
@JinghuiZhou I'm also not able to find any links to pretrained models.
