### ISSUE TITLE
你好，很高兴能学习你的开源项目，请问这个项目有对应的论文么？期待你的回答~

### ISSUE THREAD

**Issue by HJW0522** [JinghuiZhou/awesome_face_antispoofing#8]

**Comment by HJW0522** [comment]
你好，还有一个问题就是你提供的数据包含.pickle文件，请问这些是如何得到到呢？因为我使用别的数据集训练的时候报错没有对应的.pickle文件~

**Comment by JinghuiZhou** [comment]
Hello, this project is a startup version of my research，our experiment is not over. This pickle is produced by a face_alignment Python script，you can check my readme.

**Comment by JinghuiZhou** [comment]
If our paper is accepted，I will refresh my readme. Thx for your focusing.

**Comment by HJW0522** [comment]
> If our paper is accepted，I will refresh my readme. Thx for your focusing.

非常感谢解答，还有个问题请教一下: .pickle文件中保存的是对应图片的所有特征点的坐标嘛？

**Comment by JinghuiZhou** [comment]
pickle file save the （x，y）coordinates of landmarks for warping the face.
