### ISSUE TITLE
不能下载谷歌的文件

### ISSUE THREAD

**Issue by zhouyongxiu** [JinghuiZhou/awesome_face_antispoofing#9]
你好，请问一下可以放个百度网盘的链接吗，谷歌的下载总是出错

**Comment by JinghuiZhou** [comment]
OK， I will upload files and update it in readme.

**Comment by JinghuiZhou** [comment]
I have uploaded them. You can find the link in readme.

**Comment by zhouyongxiu** [comment]
@JinghuiZhou 非常感谢
